import { PopularMoviesData } from "@/entities/movies/model/types";

export const popularMoviesData: PopularMoviesData = [
    {
        moviesChainParams: {
            chainName: "Боевики",
            moviesParams: {
                type: "movie",
                isSeries: false,
                year: "2023-2024",
                "rating.kp": "7.2-10",
                "genres.name": "боевик",
            },
        },
        movies: [
            {
                id: 5626370,
                name: "Парень с вещмешком",
                alternativeName: "Bad Business",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description:
                    "Бездомный ветеран путешествует автостопом, становится бандитом и вступает в войну с главарем криминальной империи.",
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 7.3,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 45,
                    imdb: 42,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: null,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/4486362/5f26a2a4-cbb3-4b84-9a2f-1edbbadb6322/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/4486362/5f26a2a4-cbb3-4b84-9a2f-1edbbadb6322/x1000",
                },
                genres: [
                    {
                        name: "боевик",
                    },
                    {
                        name: "триллер",
                    },
                    {
                        name: "драма",
                    },
                    {
                        name: "криминал",
                    },
                    {
                        name: "приключения",
                    },
                    {
                        name: "военный",
                    },
                ],
                countries: [
                    {
                        name: "США",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 5927246,
                name: null,
                alternativeName: "WWE Clash at the Castle: Scotland",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description: null,
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 6.9,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 8,
                    imdb: 209,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: null,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                genres: [
                    {
                        name: "боевик",
                    },
                    {
                        name: "спорт",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 5926477,
                name: "Дикий клинок незнакомцев",
                alternativeName: "Mo lu kuang dao",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description:
                    "Продавец угля оказывается втянут в политический заговор, когда спасает возлюбленную убитого принца и их малолетнего сына от преследования имперских солдат.",
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 6.5,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 12,
                    imdb: 80,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: 102,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/4483445/12aa16a6-51cb-45d1-936f-738f27ae4dd6/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/4483445/12aa16a6-51cb-45d1-936f-738f27ae4dd6/x1000",
                },
                genres: [
                    {
                        name: "боевик",
                    },
                ],
                countries: [
                    {
                        name: "Китай",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 6003107,
                name: null,
                alternativeName: "Dange",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description: null,
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 5.4,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 1,
                    imdb: 661,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: 154,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                genres: [
                    {
                        name: "боевик",
                    },
                    {
                        name: "драма",
                    },
                ],
                countries: [
                    {
                        name: "Индия",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 5927239,
                name: null,
                alternativeName: "The Hunger Games: Sunrise on the Reaping",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2026,
                description: null,
                shortDescription: null,
                status: "announced",
                rating: {
                    kp: 0,
                    imdb: 0,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 0,
                    imdb: 0,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: null,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                genres: [
                    {
                        name: "фантастика",
                    },
                    {
                        name: "фэнтези",
                    },
                    {
                        name: "боевик",
                    },
                    {
                        name: "триллер",
                    },
                    {
                        name: "приключения",
                    },
                ],
                countries: [
                    {
                        name: "США",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 5921675,
                name: null,
                alternativeName: "Elyas",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description: null,
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 5.8,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 10,
                    imdb: 137,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: 99,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/10900341/0c2ffaf0-7a07-47eb-a07e-68e2f1d697d2/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/10900341/0c2ffaf0-7a07-47eb-a07e-68e2f1d697d2/x1000",
                },
                genres: [
                    {
                        name: "боевик",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
                countries: [
                    {
                        name: "Бельгия",
                    },
                    {
                        name: "Франция",
                    },
                ],
            },
            {
                id: 5613218,
                name: null,
                alternativeName: "How to Rob a Bank",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description: null,
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 6.6,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 12,
                    imdb: 2367,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: 88,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                genres: [
                    {
                        name: "документальный",
                    },
                    {
                        name: "боевик",
                    },
                    {
                        name: "криминал",
                    },
                ],
                countries: [
                    {
                        name: "США",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 6022388,
                name: "Красная нить",
                alternativeName: null,
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2017,
                description:
                    "Обычный сталкер по кличке Феликс берётся за простое, на первый взгляд, дело. Он должен обнаружить и доставить артефакт. Планы мужчины о лёгких деньгах оборачиваются для него крупными неприятностями. За голову сталкера назначена награда.",
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 0,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 0,
                    imdb: 0,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: 31,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: 18,
                genres: [
                    {
                        name: "короткометражка",
                    },
                    {
                        name: "фантастика",
                    },
                    {
                        name: "боевик",
                    },
                ],
                countries: [
                    {
                        name: "Россия",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
            {
                id: 5935174,
                name: "Континентальный раскол",
                alternativeName: "Continental Split",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: 2024,
                description:
                    "Ново-Мадридский разлом угрожает разорвать США пополам, и предотвратить катастрофу может только команда сейсмологов и правительственных агентов.",
                shortDescription: null,
                status: null,
                rating: {
                    kp: 0,
                    imdb: 4.1,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 85,
                    imdb: 257,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: 88,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/9784475/fa4731ea-f1f0-43ab-a5c6-4a594703a739/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/9784475/fa4731ea-f1f0-43ab-a5c6-4a594703a739/x1000",
                },
                genres: [
                    {
                        name: "боевик",
                    },
                    {
                        name: "триллер",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
                countries: [
                    {
                        name: "США",
                    },
                ],
            },
            {
                id: 5699476,
                name: null,
                alternativeName: "Above the Below",
                enName: null,
                type: "movie",
                typeNumber: 1,
                year: null,
                description: null,
                shortDescription: null,
                status: "post-production",
                rating: {
                    kp: 0,
                    imdb: 0,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                votes: {
                    kp: 0,
                    imdb: 0,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: 0,
                },
                movieLength: null,
                totalSeriesLength: null,
                seriesLength: null,
                ratingMpaa: null,
                ageRating: null,
                genres: [
                    {
                        name: "фантастика",
                    },
                    {
                        name: "боевик",
                    },
                    {
                        name: "триллер",
                    },
                ],
                countries: [
                    {
                        name: "Великобритания",
                    },
                ],
                top10: null,
                top250: null,
                isSeries: false,
                ticketsOnSale: false,
            },
        ],
    },
];
